# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

handleGHRelease: true
packageName: genai-toolbox
releaseType: simple
versionFile: "cmd/version.txt"
extraFiles: [
    "README.md",
    "docs/en/documentation/getting-started/colab_quickstart.ipynb",
    "docs/en/documentation/introduction/_index.md",
    "docs/en/documentation/getting-started/mcp_quickstart/_index.md",
    "docs/en/documentation/getting-started/quickstart/shared/configure_toolbox.md",
    "docs/en/integrations/alloydb/_index.md",
    "docs/en/integrations/alloydb/mcp_quickstart.md",
    "docs/en/integrations/alloydb/ai-nl/alloydb_ai_nl.ipynb",
    "docs/en/integrations/bigquery/local_quickstart.md",
    "docs/en/integrations/bigquery/mcp_quickstart/_index.md",
    "docs/en/integrations/bigquery/colab_quickstart_bigquery.ipynb",
    "docs/en/integrations/looker/looker_gemini.md",
    "docs/en/integrations/looker/looker_gemini_oauth/_index.md",
    "docs/en/integrations/looker/looker_mcp_inspector/_index.md",
    "docs/en/documentation/connect-to/ides/looker_mcp.md",
    "docs/en/documentation/connect-to/ides/mysql_mcp.md",
    "docs/en/documentation/connect-to/ides/mssql_mcp.md",
    "docs/en/documentation/connect-to/ides/postgres_mcp.md",
    "docs/en/documentation/connect-to/ides/neo4j_mcp.md",
    "docs/en/documentation/connect-to/ides/sqlite_mcp.md",
    "docs/en/documentation/connect-to/ides/oracle_mcp.md",
    "gemini-extension.json",
    {
        "type": "json",
        "path": "server.json",
        "jsonpath": "$.version"
    },
    {
        "type": "json",
        "path": "server.json",
        "jsonpath": "$.packages[0].identifier"
    },
]
